// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

models/cm_v3/otis.mdl
models/cm_v3/zombie_barney.mdl
models/cm_v3/zombie_soldier.mdl
models/cubemath/skull.mdl
models/hlclassic/p_desert_eagle.mdl
models/hlclassic/p_m40a1.mdl
models/hlclassic/p_saw.mdl
models/hlclassic/saw_shell.mdl
models/hlclassic/v_desert_eagle.mdl
models/hlclassic/v_m40a1.mdl
models/hlclassic/v_saw.mdl
models/hlclassic/w_desert_eagle.mdl
models/hlclassic/w_m40a1.mdl
models/hlclassic/w_m40a1clip.mdl
models/hlclassic/w_saw.mdl
models/hlclassic/w_saw_clip.mdl
models/mikk/hlclassic/massn.mdl
models/mikk/misc/lambda.mdl
models/mikk/misc/limitless_potential.mdl
models/mikk/monsters/zombie_hev.mdl
models/mikk/residualpoint/aworker.mdl
models/mikk/residualpoint/hgrunt.mdl
models/mikk/residualpoint/hgrunt_opfor.mdl
models/mikk/residualpoint/hlclassic/aworker.mdl
models/mikk/residualpoint/hlclassic/civ_scientist.mdl
models/mikk/residualpoint/hlclassic/hgrunt.mdl
models/mikk/residualpoint/hlclassic/hgrunt_opfor.mdl
models/mikk/residualpoint/hlclassic/ngrunt.mdl
models/mikk/residualpoint/hlclassic/v_357.mdl
models/mikk/residualpoint/hlclassic/v_9mmar.mdl
models/mikk/residualpoint/hlclassic/v_9mmhandgun.mdl
models/mikk/residualpoint/hlclassic/v_crossbow.mdl
models/mikk/residualpoint/hlclassic/v_crowbar.mdl
models/mikk/residualpoint/hlclassic/v_desert_eagle.mdl
models/mikk/residualpoint/hlclassic/v_egon.mdl
models/mikk/residualpoint/hlclassic/v_gauss.mdl
models/mikk/residualpoint/hlclassic/v_grenade.mdl
models/mikk/residualpoint/hlclassic/v_m40a1.mdl
models/mikk/residualpoint/hlclassic/v_medkit.mdl
models/mikk/residualpoint/hlclassic/v_rpg.mdl
models/mikk/residualpoint/hlclassic/v_satchel.mdl
models/mikk/residualpoint/hlclassic/v_satchel_radio.mdl
models/mikk/residualpoint/hlclassic/v_saw.mdl
models/mikk/residualpoint/hlclassic/v_shotgun.mdl
models/mikk/residualpoint/hlclassic/v_squeak.mdl
models/mikk/residualpoint/hlclassic/v_tripmine.mdl
models/mikk/residualpoint/hlclassic/w_bloodly_9mmar.mdl
models/mikk/residualpoint/hlclassic/w_bloodly_shotgun.mdl
models/mikk/residualpoint/hlclassic/xenocrab.mdl
models/mikk/residualpoint/hlclassic/zgrunt.mdl
models/mikk/residualpoint/level_change.spr
models/mikk/residualpoint/ngrunt.mdl
models/mikk/residualpoint/v_357.mdl
models/mikk/residualpoint/v_9mmar.mdl
models/mikk/residualpoint/v_9mmhandgun.mdl
models/mikk/residualpoint/v_crossbow.mdl
models/mikk/residualpoint/v_crowbar.mdl
models/mikk/residualpoint/v_desert_eagle.mdl
models/mikk/residualpoint/v_displacer.mdl
models/mikk/residualpoint/v_egon.mdl
models/mikk/residualpoint/v_gauss.mdl
models/mikk/residualpoint/v_grenade.mdl
models/mikk/residualpoint/v_m16a2.mdl
models/mikk/residualpoint/v_m40a1.mdl
models/mikk/residualpoint/v_medkit.mdl
models/mikk/residualpoint/v_rpg.mdl
models/mikk/residualpoint/v_satchel.mdl
models/mikk/residualpoint/v_satchel_radio.mdl
models/mikk/residualpoint/v_saw.mdl
models/mikk/residualpoint/v_shotgun.mdl
models/mikk/residualpoint/v_squeak.mdl
models/mikk/residualpoint/v_tripmine.mdl
models/mikk/residualpoint/w_bloodly_9mmar.mdl
models/mikk/residualpoint/w_bloodly_shotgun.mdl
models/mikk/residualpoint/w_suit.mdl
models/mikk/residualpoint/xenocrab.mdl
models/mikk/residualpoint/zgrunt.mdl
models/mikk/weapons/v_teleporter.mdl
models/mikk/weapons/w_teleporter.mdl
residualpoint.wad
sound/hlclassic/weapons/desert_eagle_reload.wav
sound/hlclassic/weapons/saw_reload.wav
sound/hlclassic/weapons/saw_reload2.wav
sound/hlclassic/weapons/sniper_bolt1.wav
sound/hlclassic/weapons/sniper_bolt2.wav
sound/hlclassic/weapons/sniper_fire.wav
sound/hlclassic/weapons/sniper_reload_first_seq.wav
sound/hlclassic/weapons/sniper_reload_second_seq.wav
sound/mikk/residualpoint/ambience/alien_fazzle1.wav
sound/mikk/residualpoint/barney/ba_late.wav
sound/mikk/residualpoint/barney/ba_security2_desk0.wav
sound/mikk/residualpoint/barney/ok03x_ba_topside.wav
sound/mikk/residualpoint/barney/s02ba_hello.wav
sound/mikk/residualpoint/barney/s02ba_pl_door.wav
sound/mikk/residualpoint/barney/sk02_ba_headdown.wav
sound/mikk/residualpoint/fgrunt/ok03b_fg01.wav
sound/mikk/residualpoint/otis/of1a1_ot0.wav
sound/mikk/residualpoint/otis/of1a1_ot2.wav
sound/mikk/residualpoint/scientist/dk01_sci_talk.wav
sound/mikk/residualpoint/scientist/sci_portopen.wav
sprites/hl_weapons//weapon_hlpython.txt
sprites/hl_weapons//weapon_ofeagle.txt
sprites/hl_weapons//weapon_ofm249.txt
sprites/hl_weapons//weapon_ofshockrifle.txt
sprites/hl_weapons//weapon_ofsniperrifle.txt
