// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

models/mikk/monsters/zombie_hev.mdl
models/mikk/residualpoint/aworker.mdl
models/mikk/residualpoint/barney.mdl
models/mikk/residualpoint/cleansuit_scientist.mdl
models/mikk/residualpoint/hgrunt.mdl
models/mikk/residualpoint/hgrunt_opfor.mdl
models/mikk/residualpoint/lambda.mdl
models/mikk/residualpoint/ngrunt.mdl
models/mikk/residualpoint/otis.mdl
models/mikk/residualpoint/v_357.mdl
models/mikk/residualpoint/v_9mmar.mdl
models/mikk/residualpoint/v_9mmhandgun.mdl
models/mikk/residualpoint/v_crossbow.mdl
models/mikk/residualpoint/v_crowbar.mdl
models/mikk/residualpoint/v_desert_eagle.mdl
models/mikk/residualpoint/v_displacer.mdl
models/mikk/residualpoint/v_egon.mdl
models/mikk/residualpoint/v_gauss.mdl
models/mikk/residualpoint/v_handgrenade.mdl
models/mikk/residualpoint/v_m16a2.mdl
models/mikk/residualpoint/v_m40a1.mdl
models/mikk/residualpoint/v_medkit.mdl
models/mikk/residualpoint/v_pipe_wrench.mdl
models/mikk/residualpoint/v_rpg.mdl
models/mikk/residualpoint/v_satchel.mdl
models/mikk/residualpoint/v_satchel_radio.mdl
models/mikk/residualpoint/v_saw.mdl
models/mikk/residualpoint/v_shotgun.mdl
models/mikk/residualpoint/v_squeak.mdl
models/mikk/residualpoint/v_tripmine.mdl
models/mikk/residualpoint/v_uzi.mdl
models/mikk/residualpoint/w_bloodly_9mmar.mdl
models/mikk/residualpoint/w_bloodly_shotgun.mdl
models/mikk/residualpoint/w_suit.mdl
models/mikk/residualpoint/woodgibs2.mdl
models/mikk/residualpoint/xenocrab.mdl
models/mikk/residualpoint/zgrunt.mdl
models/mikk/weapons/v_teleporter.mdl
models/mikk/weapons/w_teleporter.mdl
models/player/cl_scientist1/cl_scientist1.bmp
models/player/cl_scientist1/cl_scientist1.mdl
models/player/cl_scientist2/cl_scientist2.bmp
models/player/cl_scientist2/cl_scientist2.mdl
models/player/cl_scientist3/cl_scientist3.bmp
models/player/cl_scientist3/cl_scientist3.mdl
models/player/cl_scientist4/cl_scientist4.bmp
models/player/cl_scientist4/cl_scientist4.mdl
residualpoint.wad
sound/mikk/residualpoint/barney/ba_late.wav
sound/mikk/residualpoint/barney/ba_security2_desk0.wav
sound/mikk/residualpoint/barney/ok03x_ba_topside.wav
sound/mikk/residualpoint/barney/s02ba_hello.wav
sound/mikk/residualpoint/barney/s02ba_pl_door.wav
sound/mikk/residualpoint/barney/sk02_ba_headdown.wav
sound/mikk/residualpoint/boss/final_hit.ogg
sound/mikk/residualpoint/boss/first_hit.ogg
sound/mikk/residualpoint/boss/tube_prepare.ogg
sound/mikk/residualpoint/fgrunt/ok03b_fg01.wav
sound/mikk/residualpoint/otis/of1a1_ot0.wav
sound/mikk/residualpoint/otis/of1a1_ot2.wav
sound/mikk/residualpoint/scientist/dk01_sci_talk.wav
sound/mikk/residualpoint/scientist/sc_crazer.wav
sound/mikk/residualpoint/scientist/sc_helloh.wav
sound/mikk/residualpoint/scientist/sci_portopen.wav
sprites/hl_weapons/weapon_hlsatchel.txt
