// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

models/cm_v3/otis.mdl
models/cm_v3/zombie_barney.mdl
models/cm_v3/zombie_soldier.mdl
models/cubemath/arrow2d.mdl
models/cubemath/skull.mdl
models/hlclassic/p_desert_eagle.mdl
models/hlclassic/p_m40a1.mdl
models/hlclassic/p_saw.mdl
models/hlclassic/saw_shell.mdl
models/hlclassic/v_desert_eagle.mdl
models/hlclassic/v_m40a1.mdl
models/hlclassic/v_saw.mdl
models/hlclassic/w_desert_eagle.mdl
models/hlclassic/w_m40a1.mdl
models/hlclassic/w_m40a1clip.mdl
models/hlclassic/w_saw.mdl
models/hlclassic/w_saw_clip.mdl
models/mikk/hlclassic/massn.mdl
models/mikk/misc/limitless_potential.mdl
models/mikk/monsters/zombie_hev.mdl
models/mikk/residualpoint/aworker.mdl
models/mikk/residualpoint/hgrunt_opfor.mdl
models/mikk/residualpoint/hlclassic/aworker.mdl
models/mikk/residualpoint/hlclassic/hgrunt_opfor.mdl
models/mikk/residualpoint/hlclassic/ngrunt.mdl
models/mikk/residualpoint/hlclassic/w_bloodly_9mmar.mdl
models/mikk/residualpoint/hlclassic/w_bloodly_shotgun.mdl
models/mikk/residualpoint/hlclassic/xenocrab.mdl
models/mikk/residualpoint/hlclassic/zgrunt.mdl
models/mikk/residualpoint/level_change.spr
models/mikk/residualpoint/ngrunt.mdl
models/mikk/residualpoint/w_bloodly_9mmar.mdl
models/mikk/residualpoint/w_bloodly_shotgun.mdl
models/mikk/residualpoint/xenocrab.mdl
models/mikk/residualpoint/zgrunt.mdl
models/mikk/weapons/v_teleporter.mdl
models/mikk/weapons/w_teleporter.mdl
rplobbyv2.wad
sound/hlclassic/weapons/desert_eagle_reload.wav
sound/hlclassic/weapons/saw_reload.wav
sound/hlclassic/weapons/saw_reload2.wav
sound/hlclassic/weapons/sniper_bolt1.wav
sound/hlclassic/weapons/sniper_bolt2.wav
sound/hlclassic/weapons/sniper_fire.wav
sound/hlclassic/weapons/sniper_reload_first_seq.wav
sound/hlclassic/weapons/sniper_reload_second_seq.wav
sound/mikk/music/jazy_intro.mp3
sound/mikk/music/permadeath.mp3
sound/mikk/residualpoint/barney/ba_late.wav
sound/mikk/residualpoint/barney/ba_security2_desk0.wav
sound/mikk/residualpoint/barney/ok03x_ba_topside.wav
sound/mikk/residualpoint/barney/s02ba_hello.wav
sound/mikk/residualpoint/barney/s02ba_pl_door.wav
sound/mikk/residualpoint/barney/sk02_ba_headdown.wav
sound/mikk/residualpoint/fgrunt/ok03b_fg01.wav
sound/mikk/residualpoint/otis/of1a1_ot0.wav
sound/mikk/residualpoint/otis/of1a1_ot2.wav
sound/mikk/residualpoint/scientist/dk01_sci_talk.wav
sound/mikk/residualpoint/scientist/sci_portopen.wav
sprites/hl_weapons//weapon_hlpython.txt
sprites/hl_weapons//weapon_ofeagle.txt
sprites/hl_weapons//weapon_ofm249.txt
sprites/hl_weapons//weapon_ofshockrifle.txt
sprites/hl_weapons//weapon_ofsniperrifle.txt
