name: Release

on:
  push:
    tags:
      - "*"

jobs:
  release:
    name: Release
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Zip assets
      run: Compress-Archive -Path svencoop_addon -DestinationPath svencoop_addon.zip

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: game-assets
        path: svencoop_addon.zip

    - name: Upload Release
      if: startsWith( github.ref_name, 'v' )
      uses: xresloader/upload-to-github-release@v1.6.0
      with:
        file: svencoop_addon.zip
        token: ${{ secrets.TOKEN }}
        default_release_name: Residual Point
        default_release_body_path: changelog.md
        tag_name: ${{ github.ref_name }}
        draft: false
